config-1-attributes:
  value: 345                          #对应单个值
  valueArray: 1,2,3,4,5,6,7,8,9      #对应数组
  valueList:                         #对应list
    -13579
    -246810
  valueMap:                          #对应map
    name: lili
    age: 20
    sex: 男
  valueMapList:                      #对应list<map>
    - name: bob
      age: 21
    - name: caven
      age: 31

props:

  Keyword:
     bankTax: 协议扣税|缴税
       
     bankFee: 手续费|收费项目|短信服务费

     bankSecurity: 社保|社会保险

     bankSalary: 工资|发放工资
       
     bankExpense: 报销|报销费用
     
     bankInterest: 结息|利息
     
     bankVATAndAdditionalTax: 增值税及附加税
     
     bankVAT: 增值税
     
     bankAdditionanlTax: 附加税
     
     bankIncomeTax: 企业所得税
     
     bankPersonalTax: 个人所得税

              
  companies:
     YYKJ: 
        name: 深圳市宜源科技有限公司
        cost: 140501
        cj: 222108
        jyf: 222113
        dfjyf: 222114
        yfgz: 221101
        bankFee: 560303
        DefaultVTARate: 0.13
        personSecurityAmout: 5156
         
     AOKJ: 
        name: 深圳市安欧科技有限公司 
        cost: 520201
        cj: 222103
        jyf: 222104
        dfjyf: 222105
        yfgz: 221101
        bankFee: 560303
        DefaultVTARate: 0.06
        personSecurityAmout: 214
     CHKJ: 
        name: 深圳市创和技术有限公司 
        cost: 140501
        cj: 222108
        jyf: 222113
        yfgz: 221101
        dfjyf: 222114
        bankFee: 560303
        DefaultVTARate: 0.13
        personSecurityAmout: 421
      